### ISSUE TITLE
AddBorder v1.4.1 crashed VirtualDub - crash report -- build 35491 (release)

### ISSUE THREAD

**Issue by sunny-ko** [jpsdr/Filtres_JPSDR#1]
Hello from German!
My first Post on GitHub!

Here my Problem:
AddBorder v1.4.1:
Input: 720x576
Click "Cropping"
change Y2 offset to "10"
click "okay"
Output: 720x566

Click "Configure"
change Bottom to "10" 
click "okay"
click "okay"
VirtualDub crashed.

Notice: When change Bottom to "8" works. "10" crashed!

Please help!

`VirtualDub crash report -- build 35491 (release)
--------------------------------------

Disassembly:
668298e0: 0c0e            or     al, 0eh
668298e2: 0000            add    [eax], al
668298e4: 0fb6820d0e0000  movzx  eax, byte ptr [edx+e0d]
668298eb: 88830d0e0000    mov    [ebx+e0d], al
668298f1: 8b820e0e0000    mov    eax, [edx+e0e]
668298f7: 89830e0e0000    mov    [ebx+e0e], eax
668298fd: 668b82120e0000  mov    ax, [edx+e12]
66829904: 5f              pop    edi
66829905: 668983120e0000  mov    [ebx+e12], ax
6682990c: 8bc3            mov    eax, ebx
6682990e: 5e              pop    esi
6682990f: 5b              pop    ebx
66829910: c20400          ret    0004
66829913: cc              int    3
66829914: cc              int    3
66829915: cc              int    3
66829916: cc              int    3
66829917: cc              int    3
66829918: cc              int    3
66829919: cc              int    3
6682991a: cc              int    3
6682991b: cc              int    3
6682991c: cc              int    3
6682991d: cc              int    3
6682991e: cc              int    3
6682991f: cc              int    3
66829920: f644240401      test   [esp+04h], 01h
66829925: 56              push   esi
66829926: 8bf1            mov    esi, ecx
66829928: c70628c68366    mov    dword ptr [esi], 6683c628
6682992e: 740e            jz     6682993e
66829930: 68180e0000      push   00000e18
66829935: 56              push   esi
66829936: e8fe010100      call   66839b39
6682993b: 83c408          add    esp, 08h
6682993e: 8bc6            mov    eax, esi
66829940: 5e              pop    esi
66829941: c20400          ret    0004
66829944: cc              int    3
66829945: cc              int    3
66829946: cc              int    3
66829947: cc              int    3
66829948: cc              int    3
66829949: cc              int    3
6682994a: cc              int    3
6682994b: cc              int    3
6682994c: cc              int    3
6682994d: cc              int    3
6682994e: cc              int    3
6682994f: cc              int    3
66829950: 55              push   ebp
66829951: 8bec            mov    ebp, esp
66829953: 57              push   edi
66829954: fc              cld    
66829955: 8b7d08          mov    edi, [ebp+08h]
66829958: 8b4d0c          mov    ecx, [ebp+0ch]
6682995b: 8b4510          mov    eax, [ebp+10h]
6682995e: 0bc9            or     ecx, ecx
66829960: 7402            jz     66829964
66829962: f3ab            rep    stosd      <-- FAULT
66829964: 5f              pop    edi
66829965: c9              leave  
66829966: c3              ret    
66829967: cc              int    3
66829968: cc              int    3
66829969: cc              int    3
6682996a: cc              int    3
6682996b: cc              int    3
6682996c: cc              int    3
6682996d: cc              int    3
6682996e: cc              int    3
6682996f: cc              int    3
66829970: 55              push   ebp
66829971: 8bec            mov    ebp, esp
66829973: 56              push   esi
66829974: 57              push   edi
66829975: 53              push   ebx
66829976: 8b7508          mov    esi, [ebp+08h]
66829979: 8b5d0c          mov    ebx, [ebp+0ch]
6682997c: 8b5510          mov    edx, [ebp+10h]
6682997f: 8b7d14          mov    edi, [ebp+14h]
66829982: 8b4d18          mov    ecx, [ebp+18h]
66829985: fc              cld    
66829986: 8a4601          mov    al, [esi+01h]
66829989: 8a22            mov    ah, [edx]
6682998b: 42              inc    edx
6682998c: c1e010          shl    eax, 10h
6682998f: 66ad            lodsw  
66829991: 8a23            mov    ah, [ebx]
66829993: 43              inc    ebx
66829994: ab              stosd  
66829995: e2ef            loop   66829986
66829997: 5b              pop    ebx
66829998: 5f              pop    edi
66829999: 5e              pop    esi
6682999a: c9              leave  
6682999b: c3              ret    
6682999c: 55              push   ebp
6682999d: 8bec            mov    ebp, esp
6682999f: 56              push   esi
668299a0: 57              push   edi
668299a1: 53              push   ebx
668299a2: 8b7508          mov    esi, [ebp+08h]
668299a5: 8b5d0c          mov    ebx, [ebp+0ch]
668299a8: 8b5510          mov    edx, [ebp+10h]
668299ab: 8b7d14          mov    edi, [ebp+14h]
668299ae: 8b4d18          mov    ecx, [ebp+18h]
668299b1: fc              cld    
668299b2: 66ad            lodsw  
668299b4: 8a02            mov    al, [edx]
668299b6: 42              inc    edx
668299b7: c1e010          shl    eax, 10h
668299ba: 8a66fe          mov    ah, [esi-02h]
668299bd: 8a03            mov    al, [ebx]
668299bf: 43              inc    ebx
668299c0: ab              stosd  
668299c1: e2ef            loop   668299b2
668299c3: 5b              pop    ebx
668299c4: 5f              pop    edi
668299c5: 5e              pop    esi
668299c6: c9              leave  
668299c7: c3              ret    
668299c8: 55              push   ebp
668299c9: 8bec            mov    ebp, esp
668299cb: 56              push   esi
668299cc: 57              push   edi
668299cd: 53              push   ebx
668299ce: 8b7508          mov    esi, [ebp+08h]
668299d1: 8b5d0c          mov    ebx, [ebp+0ch]
668299d4: 8b5510          mov    edx, [ebp+10h]
668299d7: 8b7d14          mov    edi, [ebp+14h]
668299da: 8b4d18          mov    ecx, [ebp+18h]
668299dd: 33c0            xor    eax, eax
668299df: d1              db     0d1h

Built on Althena on Sun Oct 27 15:59:07 2013 using compiler version 1400

Windows 6.1 (Windows 7 x64 build 7601) [Service Pack 1]
Memory status: virtual free 1723M/2048M, commit limit 16252M, physical total 8127M

EAX = 80108010
EBX = 07859cc0
ECX = 000000d0
EDX = 00000564
EBP = 0018f9ec
ESI = 07c30b8c
EDI = 0785b000
ESP = 0018f9e8
EIP = 66829962
EFLAGS = 00010206
FPUCW = 027f
FPUTW = ffff

Crash reason: Access Violation

Crash context:
An out-of-bounds memory access (access violation) occurred in module 'Filtres_JPSDR'...

...writing address 0785B000...

...while running filter "AddBorder v1.4.1" (FilterInstance.cpp:2198).

Pointer dumps:

EBX   07859cc0: 80108010 80108010 80108010 80108010 80108010 80108010 80108010 80108010
ESI   07c30b88: 07c30b8c 6683c678 07c30040 00000000 006af2dc 00020202 00000000 070e16a0
ESP   0018f9e8: 00000010 071a42e0 667b3ef5 07859cc0 000005a0 80108010 00000000 00000000
      0018fa08: 07c30040 07c30038 0000022a 6681a4e1 0043e377 07c30040 006af2dc 02340ee8
      0018fa28: 07c30038 0018fb08 0233f700 00000000 00000000 3f800000 00000000 00000000
      0018fa48: 00000000 023ecf90 0062f7d4 0000088d 0062f7d4 00000896 0062f8c0 6683c42c
EBP   0018f9e8: 00000010 071a42e0 667b3ef5 07859cc0 000005a0 80108010 00000000 00000000
      0018fa08: 07c30040 07c30038 0000022a 6681a4e1 0043e377 07c30040 006af2dc 02340ee8
      0018fa28: 07c30038 0018fb08 0233f700 00000000 00000000 3f800000 00000000 00000000
      0018fa48: 00000000 023ecf90 0062f7d4 0000088d 0062f7d4 00000896 0062f8c0 6683c42c

Thread call stack:
66829962: Filtres_JPSDR!FilterModModuleInit [667b0000+66a00+12f62]
667b3ef5: Filtres_JPSDR!00003ef5
6681a4e1: Filtres_JPSDR!FilterModModuleInit [667b0000+66a00+3ae1]
0043e377: FilterInstance::RunFilterInner()
0043a120: VDFilterFrameManualSource::GetNextRequest()
0043baea: VDFilterFrameVideoSource::RunRequests()
0044062a: _catch$?RunFilter@FilterInstance@@IAEXXZ$0()
004410ea: FilterInstance::RunProcess()
004480a4: FilterSystem::Run()
00471f46: VDProject::UpdateFrame()
00447dc0: FilterSystem::RequestFrame()
004740cb: VDProject::DisplayFrame()
0047498f: VDProject::UpdateFilterList()
00478187: VDProjectUI::SetVideoFiltersAsk()
757c81c8: USER32!IsProcessDPIAware [757b0000+181a6+22]
757c8326: USER32!GetClassNameW [757b0000+182a9+7d]
0047fef9: VDProjectUI::MenuHit()
757c6b00: USER32!gapfnScSendMessage [757b0000+15fc8+b38]
0048de10: VDUIFrame::DefProc()
00480e93: _catch$?MainWndProc@VDProjectUI@@IAEJIIJ@Z$0()
00477090: VDProjectUI::WndProc()
0048e525: VDUIFrame::StaticWndProc()
757c62fa: USER32!gapfnScSendMessage [757b0000+15fc8+332]
757c6d3a: USER32!GetThreadDesktop [757b0000+16c63+d7]
757c6ce9: USER32!GetThreadDesktop [757b0000+16c63+86]
77ad013a: ntdll!KiUserCallbackDispatcher [77ac0000+1010c+2e]
757c77c4: USER32!CharPrevW [757b0000+1768c+138]
757d71ac: USER32!PeekMessageA [757b0000+27044+168]
757c7bca: USER32!DispatchMessageA [757b0000+17bbb+f]
00460736: WinMain@16()
005fc456: __tmainCRTStartup()
75cf343d: kernel32!BaseThreadInitThunk [75ce0000+1342b+12]
77af9832: ntdll!RtlInitializeExceptionChain [77ac0000+397cf+63]
77af9805: ntdll!RtlInitializeExceptionChain [77ac0000+397cf+36]

-- End of report
`

**Comment by genlinut** [comment]
Same problem here. Any workarounds or solutions?

I tried version 1.4.0 with the same result.

**Comment by jpsdr** [comment]
Totaly forgot this...
Don't have time to investigate before at least 2 weeks.
What is the color format ? YV12/YV16/YV24 ?

**Comment by jpsdr** [comment]
Does it crash if you have 2 instance filters ? A "null" filter with the cropping, and after, the add border ?

**Comment by DiceGame465** [comment]
Hello,

I boldly guess that the other two users are here for the same reason I am, so I will try to specify the problem.
I/we? are following a tutorial, found in a german Dvd/video forum, about how to digitize old analog video formats (vhs, video8 etc.). The creator of the tutorial also describes using your filter in virtualdub to get rid of the typical flickering borders. He describes setting cropping to 10 and then adding 10 black pixels, but doing that crashes virtualdub immediately.
The input video format is a raw UYVY 4:2:2 (PAL). 

I played around a bit and the filter works if there is a difference of at least 2 between cropping and adding pixels. For example cropping 6 and adding 4 works. 
Using that method makes it impossible to recode the video using "Interlacing TFF" in Xmedia recode, but I am not a hundred percent sure these problems are related.

Also I am not well versed in this whole video and encoding thing, I am just following that tutorial.
So it could be possible that I am just using your filter incorrectly. 

Thanks for your work.

**Comment by jpsdr** [comment]
Workaround for now : Convert to YV16, either set input format to YV16 in "Video ->Color Depth -> Decompression" or add Convertformat internal filter to 4:2:2 Planar YCbCr (YV16) before the AddBorder or with ConvertToYV16() if you're using an avs script.
Issue seems specific to YUY2 format.

**Comment by jpsdr** [comment]
New release, should be fixed.
